#! /bin/bash


for iyear in $(seq 1994 2014)
    do
    for imon in $(seq -f "%02g" 1 12)
        do
	for iday in $(seq -f "%02g" 1 31)
	    do
                mv "era5_TP_MADRID_${iyear}-${imon}-${iday}.txt" "era5_TP_MADRID_AERO_${iyear}-${imon}-${iday}.txt"
	done
    done
done
